### ISSUE TITLE
Photosphere Image Quality

### ISSUE THREAD

**Issue by JpEncausse** [simplicitylab/webgl-experiments#1]
Thanks for your Photosphere experiments with BabylonJS

I have strange behavior:
- I made a photo rectangle using Android device 7000 x 3000 px
- And send it to a DIV Canvas of 700 x 300 px

The image has a good quality but displayed on the sphere it look like a bad shrink thumbnail.

I tried to play with sphere subdivs and size but nothing change. Is there a trick to get a good image quality ?

**Comment by JpEncausse** [comment]
Nervermind I suxx with canvas size ... I set a size in style instead of attribute

**Comment by simplicitylab** [comment]
No problem!
